export const educationServices = [
  {
    icon: "🎓" ,
    title: "UPU Online Registration",
    description: "Register for UPU and view results",
    slug: "upu-enrollment",
  },

{  icon: "📚",
    title: "Scholarships",
    description: "Apply for scholarships and financial aid",
    slug: "scholarships",
  },

{ icon: "💼",
    title: "PTPTN",
    description: "Apply for PTPTN loans",
    slug: "ptptn",
  },
{ icon: "🌐",
    title: "MUET",
    description: "Register for MUET examinations",
    slug: "muet",
  },
{ icon: "📜",
    title: "Transcript",
    description: "Request academic transcript",
    slug: "transcript",
  },
{ icon: "🎓",
    title: "University Registration",
    description: "Register for university programs",
    slug: "university-registration",
  },
{ icon: "💰",
    title: "Student Financial Aid",
    description: "Apply for student financial aid",
    slug: "student-financial-aid",
  },
{ icon: "🏫",
    title: "TVET",
    description: "Enroll in Technical and Vocational Education and Training programs",
    slug: "tvet",
  }
];